export const texts = {
  'day-1': $localize`Segunda`,
  'day-2': $localize`Terça`,
  'day-3': $localize`Quarta`,
  'day-4': $localize`Quinta`,
  'day-5': $localize`Sexta`,
  'day-6': $localize`Sábado`,
  'day-0': $localize`Domingo`,
  phoneAvailable: $localize`Ramal disponível`,
  clickToCall: $localize`Clique para ligar.`,
  phoneUnavailable: $localize`Ramal indisponível`,
  phoneConnected: $localize`Smartphone conectado`,
  phoneDisconnected: $localize`Smartphone desconectado`,
  minutes: $localize`minutos`,
  anonimo: $localize`Anônimo`,
  minute: $localize`minuto`,
  maxTime: $localize`Tempo máximo\:`,
  timesPerDay: $localize`Vezes por dia\:`,
  unlimitedA: $localize`Ilimitada`,
  unlimitedO: $localize`Ilimitado`,
  queues: $localize`:Filas de atendimento:Filas`,
  queue: $localize`:Fila de atendimento:Fila`,
  na: $localize`:Não disponível:N/D`,
  clientUnstable: $localize`Instabilidade na conexão com o agente`,
  ringing: $localize`:Telefone chamando:Chamando`,
  unlogged: $localize`:Agente não logado na fila:Deslogado`,
  loggedAndAttending: $localize`Logado e em atendimento`,
  loggedAndPaused: $localize`Logado e em pausa`,
  logged: $localize`:Agente logado na fila:Logado`,
  paused: $localize`:Agente em pausa:Em pausa`,
  loggedAndAvailable: $localize`Logado e disponível`,
  callBackReturn: $localize`Retorno de callback`,
  receivingCall: $localize`Recebendo chamada`,
  makingCall: $localize`Realizando chamada`,
  chat: $localize`chat`,
  chats: $localize`chats`,
  call: $localize`chamada`,
  calls: $localize`chamadas`,
  survey: $localize`:Nota de pesquisa de satisfação:avaliação`,
  surveys: $localize`:Nota de pesquisa de satisfação:avaliações`,
  unlockUser: $localize`Desbloquear agente`,
  lockUser: $localize`Bloquear agente`,
  lock: $localize`Bloquear`,
  unlock: $localize`Desbloquear`,
  noChatSelected: $localize`Nenhum chat selecionado`,
  online: $localize`Online`,
  offline: $localize`Offline`,
  available: $localize`Disponível`,
  unavailable: $localize`Indisponível`,
  logIn: $localize`Logar`,
  logOut: $localize`Deslogar`,
  noName: $localize`Sem nome`,
  naoHa: $localize`Não há`,
  file: $localize`:Arquivo de computador:Arquivo`,
  priority: $localize`Prioridade`,
  normal: $localize`Normal`,
  alta: $localize`Alta`,
  muitoAlta: $localize`Muito alta`,
  maxima: $localize`Máxima`,
  marcador: $localize`Marcador`,
  filtroDeAgentes: $localize`Filtro de agentes`,
  bloqueadoParaUsuario: $localize`Bloqueado para usuário`,
  telefonia: $localize`Telefonia`,
  numero: $localize`Número`,
  ocultarInformacoes: $localize`Ocultar informações do sistema`,
  exibirInformacoes: $localize`Exibir informações do sistema`,
  administrativa: $localize`Administrativa`,
  muitoFraca: $localize`Muito fraca`,
  fraca: $localize`Fraca`,
  regular: $localize`Regular`,
  forte: $localize`Forte`,
  muitoForte: $localize`Muito forte`,
  gravarAudio: $localize`Gravar áudio`,
  pararGravacao: $localize`Parar gravação`,
  apagarGravacao: $localize`Apagar gravação`,
  enviarGravacao: $localize`Enviar gravação`,
  sentByIvr: $localize`Enviado por URA ou automação`,
  enviarTexto: $localize`Enviar texto`,
  reabrirEm: $localize`Reabrir em`,
  reabertoEm: $localize`Reaberto em`,
  reaberturaNaoAgendada: $localize`Reabertura não agendada`,
  erroAoReabrir: $localize`Erro ao reabrir`,
  templateNaoSelecionadoOuNaoDisponivel: $localize`Template não selecionado ou não disponível.`,
  filaDesabilitada: $localize`Fila desabilitada`,
  agendamento: $localize`Agendamento`,
  jaHaviaAtendimentoAberto: $localize`Já havia um atendimento aberto com o cliente`,
  agendamentoCancelado: $localize`Agendamento cancelado por `,
  aberto: $localize`Aberto`,
  fechado: $localize`Fechado`,
  avaliacao: $localize`Avaliação`,
  aval: $localize`Aval.`,
  avaliacoes: $localize`Avaliações`,
  avals: $localize`Avals`,
  desabilitarSinalSonoro: $localize`Desabilitar sinal sonoro para novas mensagens`,
  habilitarSinalSonoro: $localize`Habilitar sinal sonoro para novas mensagens`,
  atendida: $localize`Atendida`,
  atendimento: $localize`Atendimento`,
  ocupado: $localize`Ocupado`,
  stopped: $localize`Parado`,
  naoAtendida: $localize`Não atendida`,
  falha: $localize`Falha`,
  bloqueios: $localize`Bloqueios`,
  bloqueio: $localize`Bloqueio`,
  pausa: $localize`Pausa`,
  pausas: $localize`Pausas`,
  totalDeChamadasAtendidas: $localize`Total de chamadas atendidas`,
  totalDeChamadasEncerradasPeloCliente: $localize`Total de chamadas encerradas pelo cliente`,
  totalDeChamadasEncerradasPeloAgente: $localize`Total de chamadas encerradas pelo agente`,
  totalDeChamadasTransferidasPeloAgente: $localize`Total de chamadas transferidas pelo agente`,
  tempoTotalLogado: $localize`Tempo total logado no aplicativo`,
  tempoMedioLogado: $localize`Tempo médio logado no aplicativo`,
  tempoTotalDisponivelParaAtendimentos: $localize`Tempo total disponível para atendimento (Logado em uma fila)`,
  tempoMedioDisponivelParaAtendimentos: $localize`Tempo médio disponível para atendimento (Logado em uma fila)`,
  tempoTotalEmPausaENumeroDePausas: $localize`Tempo total em pausa e número de pausas dadas`,
  tempoTotalBloqueado: $localize`Tempo total bloqueado e número de bloqueios`,
  tempoMedioEmPausa: $localize`Tempo médio em pausa e número de pausas dadas`,
  tempoMedioEmAtendimento: $localize`Tempo médio para atendimento`,
  tempoMedioEmChamada: $localize`Tempo médio em chamada`,
  tempoTotalEmChamada: $localize`Tempo total em chamada`,
  encerradosSemResposta: $localize`Encerrados sem resposta`,
  tempoMedioParaPrimeiraResposta: $localize`Tempo médio para primeira resposta`,
  logouNoAplicativo: $localize`Logou no aplicativo`,
  deslogouNoAplicativo: $localize`Deslogou do aplicativo`,
  semTextoInserido: $localize`Sem texto inserido`,
  correspondencia: $localize`Correspondência`,
  correspondencias: $localize`Correspondências`,
  semCorrespondencias: $localize`Sem correspondências`,
  encerrarAtendimento: $localize`Encerrar atendimento`,
  transferirAtendimento: $localize`Transferir atendimento`,
  buscarContato: $localize`Buscar Contato`,
  cadastrarContato: $localize`Cadastrar Contato`,
  verificarUsuario: $localize`Verificar estado de agente`,
  enviarFlow: $localize`Enviar flow`,
  limparFlow: $localize`Apagar dados da resposta do flow`,
  salvarVariavel: $localize`Salvar variável`,
  verificarAgente: $localize`Verificar agente`,
  requisicaoHttp: $localize`Requisição HTTP`,
  protocolo: $localize`Protocolo`,
  etiquetar: $localize`Etiquetar`,
  enviarPergunta: $localize`Enviar pergunta`,
  enviarArquivo: $localize`Enviar arquivo`,
  salvarInformacao: $localize`Salvar informação`,
  botaoComUrl: $localize`Botão com URL`,
  integracao: $localize`Integração`,
  enviarMensagem: $localize`Enviar mensagem`,
  cancelarEnvio: $localize`Cancelar envio`,
  removerTrigger: $localize`Remover gatilho`,
  removeAllTriggers: $localize`Remover todos os gatilhos`,
  createTask: $localize`Criar tarefa`,
  markTaskAsDone: $localize`Marcar tarefa como concluída`,
  aplicarTrava: $localize`Alterar trava`,
  executarAutomacao: $localize`Executar fluxo de automação`,
  editarContato: $localize`Editar contato`,
  aguardarMensagem: $localize`Aguardar mensagem`,
  exibirFormulario: $localize`Exibir formulário`,
  codigoJavascript: $localize`Código javascript`,
  novoAtendimento: $localize`Abrir novo atendimento`,
  compartilharContato: $localize`Compartilhar contato`,
  limparTarefas: $localize`Limpar tarefas não concluídas`,
  enviarEmail: $localize`Enviar e-mail`,
  buscarAtendimento: $localize`Buscar atendimento`,
  enviarAlertaWa: $localize`Enviar alerta por WA`,
  adicionarPersistente: $localize`Adicionar registro persistente`,
  removerPersistente: $localize`Remover registro persistente`,
  buscarPersistente: $localize`Buscar registro persistente`,
  responderComentario: $localize`Responder comentário`,
  aplicarGatilhos: $localize`Gatilhos`,
  esperar: $localize`Esperar`,
  sendTemplate: $localize`Enviar template`,
  message: $localize`Enviar mensagem`,
  question: $localize`Enviar pergunta`,
  addToWaitingList: $localize`Enviar para sala de espera`,
  removeFromWaitingList: $localize`Remover da sala de espera`,
  addOpportunity: $localize`Adicionar oportunidade`,
  editOpportunity: $localize`Editar oportunidade`,
  moveOpportunity: $localize`Mover oportunidade`,
  cloneOpportunity: $localize`Clonar oportunidade`,
  winOpportunity: $localize`Ganhar oportunidade`,
  reopenOpportunity: $localize`Reabrir oportunidade`,
  loseOpportunity: $localize`Perder oportunidade`,
  searchOpportunity: $localize`Buscar oportunidade`,
  transferOpportunity: $localize`Transferir oportunidade`,
  insertFileOpportunity: $localize`Anexar arquivo`,
  freezeOpportunity: $localize`Congelar oportunidade`,
  unfreezeOpportunity: $localize`Descongelar oportunidade`,
  searchInstance: $localize`Buscar instância`,
  createInstance: $localize`Criar instância`,
  editInstanceContactDetails: $localize`Atualizar dados de contato`,
  markInstanceForExclusion: $localize`Cancelar instância`,
  reactivateInstance: $localize`Reativar instância`,
  blockInstance: $localize`Bloquear instância`,
  unblockInstance: $localize`Desbloquear instância`,
  restartInstance: $localize`Reiniciar serviço`,
  restartInstanceContainer: $localize`Reiniciar container`,
  updateInstance: $localize`Atualizar instância`,
  getInstanceBill: $localize`Valor faturado`,
  addInformationCard: $localize`Adicionar cartão de informação`,
  addInformationCardToMessage: $localize`Adicionar cartão de informação a mensagem`,
  removeInformationCard: $localize`Remover cartão de informação`,
  removeInformationCardFromMessage: $localize`Remover cartão de informação de mensagem`,
  showSnackNotification: $localize`Exibir notificação snack`,
  aiAddContextToAssistant: $localize`Adicionar contexto ao assistente`,
  aiProcessFile: $localize`Processar com IA`,
  aiStopAssistant: $localize`Interromper assistente`,
  aiStopAssistantTooltip: $localize`Interrompe a execução de um assistente. Se o atendimento não estiver com um assistente, esse elemento será ignorado. Após a interrupção, o atendimento seguirá na URA pelo nó de transferência do assistente e a variável assistant_transfer_reason receberá o texto "execution_stopped"`,
  enviarNotificacao: $localize`Enviar notificação`,
  transferir: $localize`Transferir`,
  encerrar: $localize`Encerrar`,
  filtro: $localize`Filtro`,
  semFiltro: $localize`Sem filtro`,
  semMotivo: $localize`Sem motivo`,
  semContato: $localize`Sem contato`,
  inicioDoAtendimento: $localize`Início do atendimento`,
  timeout: $localize`Timeout`,
  nao: $localize`Não`,
  sim: $localize`Sim`,
  desativado: $localize`Desativado`,
  seg: $localize`:Abreviação de segundos:Seg.`,
  administrador: $localize`Administrador`,
  supervisor: $localize`Supervisor`,
  bot: $localize`Bot`,
  mobile: $localize`Mobile`,
  agente: $localize`Agente`,
  usuarioPonto: $localize`Usuário de ponto`,
  habilitado: $localize`Habilitado`,
  desabilitado: $localize`Desabilitado`,
  bloquear: $localize`Bloquear`,
  alertar: $localize`Alertar`,
  autenticado: $localize`Autenticado`,
  challenge: $localize`Challenge`,
  conectado: $localize`Conectado`,
  desconectado: $localize`Desconectado`,
  desconectarDoFacebook: $localize`Desconectar do Facebook`,
  entrarComFacebook: $localize`Entrar com o Facebook`,
  smartphoneConectado: $localize`Smartphone conectado`,
  smartphoneDesconectado: $localize`Smartphone desconectado`,
  socketConectado: $localize`Socket conectado`,
  socketDesconectado: $localize`Socket desconectado`,
  servidorAutenticado: $localize`Servidor autenticado`,
  servidorNaoAutenticado: $localize`Servidor não autenticado`,
  converterParaWa: $localize`Converter para WA`,
  converterParaWaMD: $localize`Converter para WA MD`,
  slaEspera: $localize`SLA Espera (s)`,
  slaPrimeiraResposta: $localize`SLA Primeira Resposta (s)`,
  ok: $localize`OK`,
  problema: $localize`Problema`,
  para: $localize`para`,
  com: $localize`com`,
  executing: $localize`Em execução`,
  noReasonRegistered: $localize`Sem motivo registrado`,
  noAutomation: $localize`Sem automação`,
  externalGroup: $localize`Grupo externo`,
  internalGroup: $localize`Grupo interno`,
  internalChat: $localize`Chat interno`,
  signatureDisabled: $localize`Assinatura desabilitada`,
  signatureEnabled: $localize`Assinatura habilitada`,
  pressToSelectACompany: $localize`Pressione para selecionar uma empresa`,
  semEtiqueta: $localize`Sem etiqueta`
};
